### ISSUE TITLE
Traceback while using MusicManager

### ISSUE THREAD

**Issue by iondulgheru** [simon-weber/gmusicapi#535] opened 2017-02-14 21:12 UTC
I get the traceback below after each run of   ```mm.upload(filepaths, enable_matching=True, enable_transcoding=True, transcode_quality=u'320k')```
```python
Traceback (most recent call last):
  File "/usr/lib64/python2.7/logging/__init__.py", line 861, in emit
    msg = self.format(record)
  File "/usr/lib64/python2.7/logging/__init__.py", line 734, in format
    return fmt.format(record)
  File "/usr/lib64/python2.7/logging/__init__.py", line 465, in format
    record.message = record.getMessage()
  File "/usr/lib64/python2.7/logging/__init__.py", line 325, in getMessage
    msg = str(self.msg)
  File "/usr/lib/python2.7/site-packages/protobuf-3.2.0-py2.7.egg/google/protobuf/internal/python_message.py", line 964, in __str__
    return text_format.MessageToString(self)
  File "/usr/lib/python2.7/site-packages/protobuf-3.2.0-py2.7.egg/google/protobuf/text_format.py", line 159, in MessageToString
    printer.PrintMessage(message)
  File "/usr/lib/python2.7/site-packages/protobuf-3.2.0-py2.7.egg/google/protobuf/text_format.py", line 326, in PrintMessage
    self.PrintField(field, value)
  File "/usr/lib/python2.7/site-packages/protobuf-3.2.0-py2.7.egg/google/protobuf/text_format.py", line 355, in PrintField
    self.PrintFieldValue(field, value)
  File "/usr/lib/python2.7/site-packages/protobuf-3.2.0-py2.7.egg/google/protobuf/text_format.py", line 391, in PrintFieldValue
    self._PrintMessageFieldValue(value)
  File "/usr/lib/python2.7/site-packages/protobuf-3.2.0-py2.7.egg/google/protobuf/text_format.py", line 376, in _PrintMessageFieldValue
    self.PrintMessage(value)
  File "/usr/lib/python2.7/site-packages/protobuf-3.2.0-py2.7.egg/google/protobuf/text_format.py", line 324, in PrintMessage
    self.PrintField(field, element)
  File "/usr/lib/python2.7/site-packages/protobuf-3.2.0-py2.7.egg/google/protobuf/text_format.py", line 355, in PrintField
    self.PrintFieldValue(field, value)
  File "/usr/lib/python2.7/site-packages/protobuf-3.2.0-py2.7.egg/google/protobuf/text_format.py", line 391, in PrintFieldValue
    self._PrintMessageFieldValue(value)
  File "/usr/lib/python2.7/site-packages/protobuf-3.2.0-py2.7.egg/google/protobuf/text_format.py", line 376, in _PrintMessageFieldValue
    self.PrintMessage(value)
  File "/usr/lib/python2.7/site-packages/protobuf-3.2.0-py2.7.egg/google/protobuf/text_format.py", line 326, in PrintMessage
    self.PrintField(field, value)
  File "/usr/lib/python2.7/site-packages/protobuf-3.2.0-py2.7.egg/google/protobuf/text_format.py", line 355, in PrintField
    self.PrintFieldValue(field, value)
  File "/usr/lib/python2.7/site-packages/protobuf-3.2.0-py2.7.egg/google/protobuf/text_format.py", line 409, in PrintFieldValue
    out.write(text_encoding.CEscape(out_value, out_as_utf8))
  File "/usr/lib/python2.7/site-packages/protobuf-3.2.0-py2.7.egg/google/protobuf/text_encoding.py", line 79, in CEscape
    return ''.join(_cescape_byte_to_str[Ord(c)] for c in text)
  File "/usr/lib/python2.7/site-packages/protobuf-3.2.0-py2.7.egg/google/protobuf/text_encoding.py", line 79, in <genexpr>
    return ''.join(_cescape_byte_to_str[Ord(c)] for c in text)
TypeError: ord() expected string of length 1, but int found
Logged from file shared.py, line 243
```

I am using the example from the documentation:
```python
from gmusicapi import Musicmanager
mm = Musicmanager()
mm.login()
mm.upload('foo.mp3')
```

At line 243 from shared.py there is this statement:
```log.debug(cls.filter_response(parsed_response))```

I tried to debug the error```TypeError: ord() expected string of length 1, but int found```, but couldn't find the problem fast. It seems that it's expecting a number formatted as a string, but is receiving a number.

```bash
[root@play gmusic]# python --version
Python 2.7.12
```

**Comment by simon-weber** [comment] 2017-02-14 22:53
I knew this sounded familiar: I think it's a duplicate of https://github.com/simon-weber/gmusicapi/issues/452. Let's take the discussion over there.

**Closed by simon-weber** 2017-02-14 22:53 UTC
