### ISSUE TITLE
__init__() takes at most 4 positional arguments (5 given)

### ISSUE THREAD

**Issue by xdragonforce** [simon-weber/gmusicapi#574] opened 2017-10-11 23:14 UTC
Get these when I run any of the scripts. Auth link is given but program crashes no matter what I paste in.

Linux ourea 4.12.4-feral #2 SMP Sat Jul 29 19:17:51 BST 2017 x86_64 GNU/Linux / Python 3.6.3

`gmsync
init() takes at most 4 positional arguments (5 given)

Visit the following url:
https://accounts.google.com/o/oauth2/v2/auth?client_id=652850857958.apps.googleusercontent.com&redirect_uri=urn%3Aietf%3Awg%3Aoauth%3A2.0%3Aoob&scope=https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fmusicmanager&access_type=offline&response_type=code
Follow the prompts, then paste the auth code here and hit enter:
Traceback (most recent call last):
File "./gmsync", line 11, in
sys.exit(main())
File "/media/sdi1/stew/.local/lib/python3.6/site-packages/gmusicapi_scripts/gmsync.py", line 110, in main
mmw.login(oauth_filename=cli['cred'], uploader_id=cli['uploader-id'])
File "/media/sdi1/stew/.local/lib/python3.6/site-packages/gmusicapi_wrapper/musicmanager.py", line 56, in login
self.api.perform_oauth(storage_filepath=oauth_cred)
File "/media/sdi1/stew/.local/lib/python3.6/site-packages/gmusicapi/clients/musicmanager.py", line 101, in perform_oauth
credentials = flow.step2_exchange(code)
File "/media/sdi1/stew/.local/lib/python3.6/site-packages/oauth2client/_helpers.py", line 133, in positional_wrapper
return wrapped(*args, **kwargs)
File "/media/sdi1/stew/.local/lib/python3.6/site-packages/oauth2client/client.py", line 2089, in step2_exchange
raise FlowExchangeError(error_msg)
oauth2client.client.FlowExchangeError: invalid_requestMissing required parameter: code

**Comment by simon-weber** [comment] 2017-10-13 19:30
Looks like this is a dupe of https://github.com/thebigmunch/gmusicapi-scripts/issues/80, so I'll close this in favor of it.

**Closed by simon-weber** 2017-10-13 19:30 UTC
