### ISSUE TITLE
GetUploadSession error 404: the request was rejected

### ISSUE THREAD

**Issue by ibaaj** [simon-weber/gmusicapi#380] opened 2015-11-11 15:10 UTC
pinned: here's a workaround to test: https://github.com/simon-weber/gmusicapi/issues/380#issuecomment-156743098

- - -

Hello,

Everytime I try to upload using gmupload.py from [gmusicapi-scripts](https://github.com/thebigmunch/gmusicapi-scripts) to google music I get  : 
```
GetUploadSession error 404: the request was rejected
```
for every song.

Then if I retry I get ``ALREADY EXISTS```.

I can't see those songs in google music.

gmusicapi 7.0.0
OpenSSL 1.0.1k 8 Jan 2015
Python 2.7.9

log from ```gmusicapi.log```

```
2015-11-11 13:51:46,380 - gmusicapi.Musicmanager1 (shared:201) [DEBUG]: ProvideSample(args=[u'/path/to/my/song/1.mp3. ...', <gmusicapi.protocol.upload_pb2.SignedChallengeInfo object at 0x7fd2d5d059b0>, <gmusicapi.protocol.locker_pb2.Track object at 0x7fd2d5d05a28>, 'XX:XX:XX:XX:XX:XX', ''], kwargs={})
2015-11-11 13:51:46,625 - gmusicapi.Musicmanager1 (shared:242) [DEBUG]: response_type: SAMPLE_RESPONSE
sample_response {
  track_sample_response {
    client_track_id: "XXXXXXXXXXXXXXXXXXXXXX"
    response_code: UPLOAD_REQUESTED
    server_track_id: "XXXXXX-XXXXXX-XXXXXX-XXXX"
    expect_match: false
  }
}
policy {
  pause_uploads: false
  abort: false
  retry_in_minutes: 5
  bandwidth_cap_kbps: 12000
  pause_downloads: false
  download_bandwidth_cap_kbps: 16000
  send_analytics: false
  enable_gapless: true
  enable_m4p: true
}

2015-11-11 13:51:46,631 - gmusicapi.Musicmanager1 (shared:201) [DEBUG]: UpdateUploadState(args=['start', 'XX:XX:XX:XX:XX:XX'], kwargs={})
2015-11-11 13:51:46,674 - gmusicapi.Musicmanager1 (shared:242) [DEBUG]: response_type: SAMPLE_RESPONSE
sample_response {
}
policy {
  pause_uploads: false
  abort: false
  retry_in_minutes: 5
  bandwidth_cap_kbps: 12000
  pause_downloads: false
  download_bandwidth_cap_kbps: 16000
  send_analytics: false
  enable_gapless: true
  enable_m4p: true
}
2015-11-11 13:51:46,681 - gmusicapi.Musicmanager1 (shared:201) [DEBUG]: GetUploadSession(args=['XX:XX:XX:XX:XX:XX', 0, <gmusicapi.protocol.locker_pb2.Track object at 0x7fd2d5d05a28>, u'/path/to/my/song. ...', u'XXXXX-XXXXX-XXXXX-XXXXXX', False], kwargs={})
2015-11-11 13:51:46,884 - gmusicapi.Musicmanager1 (shared:242) [DEBUG]: {u'errorMessage': {u'additionalInfo': {u'uploader_service.GoogleRupioAdditionalInfo': {u'completionInfo': {u'status': u'REJECTED', u'customerSpecificInfo': {u'ResponseCode': 404}}, u'requestRejectedInfo': {u'reasonDescription': u'agent_rejected'}}}, u'reason': u'REQUEST_REJECTED', u'upload_id': u'XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX'}}
2015-11-11 13:51:46,884 - gmusicapi.Musicmanager1 (musicmanager:538) [DEBUG]: problem getting upload session: the request was rejected
code=404 retrying=False
2015-11-11 13:51:52,888 - gmusicapi.Musicmanager1 (musicmanager:549) [WARNING]: giving up on upload session for '/path/to/my/song/1.mp3': GetUploadSession error 404: the request was rejected
2015-11-11 13:51:52,893 - gmusicapi.Musicmanager1 (shared:201) [DEBUG]: UpdateUploadState(args=['stopped', 'XX:XX:XX:XX:XX:XX'], kwargs={})
2015-11-11 13:51:52,937 - gmusicapi.Musicmanager1 (shared:242) [DEBUG]: response_type: SAMPLE_RESPONSE
sample_response {
}
policy {
  pause_uploads: false
  abort: false
  retry_in_minutes: 5
  bandwidth_cap_kbps: 12000
  pause_downloads: false
  download_bandwidth_cap_kbps: 16000
  send_analytics: false
  enable_gapless: true
  enable_m4p: true
}
```

**Comment by simon-weber** [comment] 2015-11-11 15:35
Hm, my build just passed: https://travis-ci.org/simon-weber/gmusicapi/jobs/86413496.

"agent_rejected" seems to suggest something about your uploader id. What format are you using?

**Comment by dickp** [comment] 2015-11-11 15:43
I'm seeing the same issue.  I'm using the gmusicapi-script tool 'gmsync', with the default uploader-id.  This has worked perfectly in the recent past.

gmusicapi v7.0.0, python 2.7.6

**Comment by ibaaj** [comment] 2015-11-11 15:46
Hi,
I use my default eth0 HWaddr (uppercase) as uploader id. I can see my device in GMusic's settings.
I retried with a fake one 
```
MacAdress=$(od -vAn -N8 -tu8 < /dev/urandom |md5sum|sed 's/^\(..\)\(..\)\(..\)\(..\)\(..\).*$/02:\1:\2:\3:\4:\5/'|tr '[:lower:]' '[:upper:]')

```
no change... still rejected, still "already exists"...

**Comment by simon-weber** [comment] 2015-11-11 15:47
Weird. When I have a chance I'll look into what my build is using, but I'm pretty sure it's a mac address of that format.

**Comment by kermes-vermilio** [comment] 2015-11-11 16:38
I get the same issue. I have been testing it with a batch of approx. 36 songs. Interestingly there are two that will pass and upload with no issues. The rest will give me the 404 error the first attempt, and will tell me they already exist thereafter.

I have attempted to use a unique ID, but that then asks me to re-confirm my account (following the URL and pasting the key) and then fails auth completely - maybe I am doing that wrong...

**Comment by caffinatedmonkey** [comment] 2015-11-11 20:52
I'm experiencing the same issue. It seemed to work fine until around the beginning of this week. I'm also out of my of my 10 authorized devices, so I can't try with a different I'd.

**Comment by thebigmunch** [comment] 2015-11-11 22:17
Just to jump on this and stay subscribed, I can confirm this behavior from both my scripts and the python interactive shell. Some songs work, some don't. The ones that don't are shown as already existing but not showing in library through gmusicapi, Google Music website, nor Android app.

**Comment by kermes-vermilio** [comment] 2015-11-12 09:23
OK I managed to work out what I was doing wrong with the unique ID (i.e. I stopped being a bellend :-D), and that successfully logged on and gave me the "404: request rejected" (rather than the "already exists" message I have been having since the first failure.

**Comment by idvoretskyi** [comment] 2015-11-13 08:14
Approve that bug exists - I have the same issue rigth now.

**Comment by simon-weber** [comment] 2015-11-13 15:37
Since nobody has figured out a pattern to their failing requests, I'm guessing google's request format changed. I'll have a chance to poke at the music manager this weekend -- hopefully it's not a big change.

**Comment by simon-weber** [comment] 2015-11-14 18:01
Huh. I just captured two non-matching uploads on the newest Music Manager. Both of them got the agent_rejected response (though with a 503, not a 404), retried with a single field changed ` "content": "jumper-uploader-title-42"` -> `"content": "jumper-uploader-title-6335"`, and then got a successful session.

I still need to recreate the error (since it's not happening from my builds); hopefully I'll be able to test this fix without pulling in you folks.

**Comment by simon-weber** [comment] 2015-11-14 18:44
Alright, I'm not sure if that part is relevant. I think the problem may actually be with scan-and-match.

This bit is new: `fingerprint_algorithm: LIGHTMP3FP_CLIENT`. I think this new step is causing problems both when scan-and-match is on, and when it's off (which we implement by sending an empty sample).

I'm going to see if an old music manager breaks on this step too. Hopefully it doesn't, which means there's some kind of backwards compatibility we can use. If it does, I'll have to upgrade to the new protos and go from there.

**Comment by simon-weber** [comment] 2015-11-14 19:26
Old music managers work fine, so we don't need to worry about the new fingerprinting algorithm.

I think client ids are part of the problem, though. I've always [computed a different one from google](https://github.com/simon-weber/gmusicapi/blob/a5c15886dde6b93708f47e0ef7e70644a405df3c/gmusicapi/protocol/musicmanager.py#L146), and it would seem that the new serverside code handles this situation differently. Some experiments:
* vanilla gmusicapi upload: 404 already_matched, server id not in library
* ^, but clientid set to what MM would compute, matching enabled: successful match
* ^, but matching _disabled_: successful match!? gmusicapi recognizes this and logs an error ["track matched without matching enabled"](https://github.com/simon-weber/gmusicapi/blob/a5c15886dde6b93708f47e0ef7e70644a405df3c/gmusicapi/clients/musicmanager.py#L491)

So it would seem that the sever now believes the client based on client id alone? The first case is really weird: it's almost as if the server is matching you to a track in someone else's library.

Hopefully the fix is just to match MM's client id generation.

**Comment by simon-weber** [comment] 2015-11-14 20:06
Ok, here's a workaround for you folks to test:
* download [eyed3](http://eyed3.nicfit.net) (`pip install eyed3`)
* pick a song that failed to upload and make a copy of it
* run `eyeD3 --remove-all copy.mp3`
* upload copy.mp3 with gmusicapi

In my tests this makes the upload successful, which validates theory about clientids.

**Comment by dickp** [comment] 2015-11-14 20:34
The eyed3 workaround didn't work for me.

Without 'scan and match' gmsync got the error 'foo.mp3 was matched without matching enabled'

With 'scan and match', gmsync looked like it was successfully uploading but then got the error "rejected: TrackSampleResponse code 4: ALREADY_EXISTS(057b86cc-03ae-370e-aad3-4f6065ba8ac5)
(1/1) Failed to upload /tmp/foo.mp3 | ALREADY EXISTS"

**Comment by simon-weber** [comment] 2015-11-14 21:14
@dickp I think that's the expected behavior. Can you check if the first attempt resulting in a song being added to your library?

**Comment by dickp** [comment] 2015-11-14 21:32
I can't see anything new in the 'Last added' list.

**Comment by simon-weber** [comment] 2015-11-14 21:43
Hm. @dickp, do you mind sending me the file so I can test with it? I wonder if it has something like ape tags throwing off the hash.

**Comment by dickp** [comment] 2015-11-14 21:58
I've emailed the file to you directly.

**Comment by simon-weber** [comment] 2015-11-15 00:11
Weird, that uploaded fine for me once I stripped the tags.

**Comment by idvoretskyi** [comment] 2015-11-15 09:08
@simon, BTW, is there any way run gm*.py scripts in debug mode?

**Comment by thebigmunch** [comment] 2015-11-15 13:26
@idvoretskyi: What do you mean by debug mode? Any logging messages from them are output to stdout. I haven't yet added writing to disk, but you could simply redirect the output to a file. To enable gmusicapi's logging while using them, use the -l option as stated in the usage docs and the scripts' help.

**Comment by idvoretskyi** [comment] 2015-11-15 20:32
@thebigmunch: I'm speaking about extended output when I run gmusicapi scripts - I receive only errors like '404', but I'd like to see the whole _requesting_ process while running them.

**Comment by kermes-vermilio** [comment] 2015-11-17 14:23
I tried using the eyed3 method on a batch of songs. now, from a list of 23 tracks, it recognises 3, matches 2, and attempts to upload 1 (but already exists). None of the tracks are in my library.

**Comment by simon-weber** [comment] 2015-11-17 15:37
Huh. So what could be different about our requests that mine are working, but nobody else's are? I even had success with a track that somebody else did not. I'm on the develop version, but there aren't any changes affecting the music manager in it.

**Comment by soncaokim** [comment] 2015-11-17 15:42
I have the issue as well (using the gmusic-script to upload songs). Worked
around by changing tag data a bit (few spaces in comment) and retry again.

Nice piece of software by the way

**Comment by simon-weber** [comment] 2015-11-17 15:44
Maybe it's the client id generation mismatch as I described before, but our results differ because of our past uploads? It seems super unlikely that the hashes would collide that much, though.

**Comment by kermes-vermilio** [comment] 2015-11-17 16:45
After using eyeD3 to remove the tags, I tried using id3tool to add some tags back in. This time It recognised that the song needed uploading, and tried, but got hit with the 404 again.

**Comment by simon-weber** [comment] 2015-11-20 05:25
@idvoretskyi I've created a branch that will log entire requests: https://github.com/simon-weber/gmusicapi/tree/proto_debug. Entire responses are already logged, so this should give you everything you're interested in.

**Comment by simon-weber** [comment] 2015-11-21 23:33
I've run a bunch of experiments and fixed a few minor differences in the scotty request, but still everything points back to the clientid.

For every track I've tried, the eyed3 workaround makes our clientid match the music manager's, and results in a successful upload with no other differences to the request. I don't have any idea why this isn't reliable for other people. I'm going to work on adding it to gmusicapi anyway -- even if it's not perfect, it's an improvement to the current situation.

**Comment by accandme** [comment] 2015-11-22 00:27
Hello,

First of all, thank you @simon-weber for this great API!

I recently started facing the same problem, and the `eyeD3 --remove-all` trick did not solve the problem. So, for now, I am completely stuck, because I cannot upload any MP3.

It would be really nice if you manage to find the source of this error and fix it.

**Comment by simon-weber** [comment] 2015-11-22 02:43
@accandme can you email me one of the original files that failed to upload? I'll try the eyed3 workaround on my end and see if I get the same result.

**Comment by dickp** [comment] 2015-11-22 11:44
After being busy all week and not touching gmusic, I now see in 'Last added' the track I uploaded without tags.  It definitely wasn't there when I looked just after attempting the upload.

So maybe it can take a while for the backend to update?

**Comment by accandme** [comment] 2015-11-22 12:14
@simon-weber I sent you a sample song that fails. 

@dickp 24 hours after attempting to upload, I still cannot see anything (new) in the gmusic interface. How long did you wait?

**Comment by simon-weber** [comment] 2015-11-22 17:03
@accandme's track is an odd one: it's the first I've seen where eyed3 makes the clientid match Google's, but then still fails to upload. I tried it on two accounts in case unsuccessful uploads put the backend into a weird state, but it fails even I upload the tagless version first.

**Comment by simon-weber** [comment] 2015-11-22 17:21
Oh, interesting, I think I managed to get the Music Manager into the state that @dickp saw: it's giving me ALREADY_EXISTS for a serverid that's not in my library, and the Music Manager is fine with it. Maybe the track will show up after waiting a while? It's been ~5 minutes already.

**Comment by patrickjahns** [comment] 2015-11-22 18:27
I am experiencing the same issue - roughly 2 weeks ago it was fine with uploading tracks. Now I tried to sync my collection again with recently added tracks. First it failed with "request rejected" and when trying again I receive "Already exists" - but the tracks don`t show up in my recently added list and I can also not find them under search

This is really strange - using music manager from google the tracks upload fine (and the last change was somewhat around August for their client)

**Comment by dickp** [comment] 2015-11-22 21:10
@accandme I don't know for sure, I just noticed it when looking this morning.  It was around a week after I last looked.

**Comment by simon-weber** [comment] 2015-11-23 00:50
@patrickjahns re "the last change was somewhat around August for their client": Google switched to a new backend [mid-september](https://github.com/simon-weber/gmusicapi/releases/tag/7.0.0) and I had been assuming this behavior was related.

**Comment by ezhikus** [comment] 2015-11-24 14:42
I see in request to https://android.clients.google.com/upsj/upauth made by Music Manager 1.0.216.5719 new parameters (there were only MAC and computer name earlier) - MAC one more time and some long id. Then this id is also used in /upsj/clientstate request body. Could it be Google added some param we don't have?

**Comment by ezhikus** [comment] 2015-11-24 15:10
Additional information. This new id I told above is string (64 chars) and it is present in every request (and in some responses). In request to "uploadsj/scottyagent" this parameter called "UploaderId". So my guess Google decided to switch from MAC adress as uploader id to some other id - this string. The initial request to "upsj/upauth" is something like a way to map "old" uploader id (mac) to a "new" and then only new id is used in requests. 

Does it make sense?

**Comment by iantpryor** [comment] 2015-11-24 15:22
Thank you @simon-weber, I'm able to upload tracks using the `eyeD3 --remove-all` workaround to strip them of their tags.  Songs with tags still give the ALREADY EXISTS error for me.

**Comment by simon-weber** [comment] 2015-11-24 17:25
@ezhikus I believe that the new uploader id is a hash of the mac address. I didn't see a difference when switching from old to new in my requests, so I didn't think it was the cause of the problem (but I also didn't dig into it very much).

**Comment by jmk2000** [comment] 2015-11-25 12:14
I'm not sure if it's relevant but I noticed that when gmusicapi uploads were complete the tracks would not show up on my sonos player. The album showed but no tracks appeared to be on it. I would have to change anything in the tags using web interface for the tracks to show on sonos.

Tracks uploaded by google music manager or via web interface showed up straight away.

**Comment by simon-weber** [comment] 2015-11-25 18:09
@jmk2000 huh, that's bizarre. Were those tracks uploaded with the eyed3 trick? If so, maybe sonos doesn't handle missing metadata fields well.

**Comment by adam-uk** [comment] 2015-11-25 22:01
Uploading stopped working for me, so I uninstalled what looks like quite an old version - gmusicapi-3.1.1_dev-py2.7.egg-info, and now have version (gmusicapi-7.0.0). I'm currently using https://github.com/Stono/google-music-sync as it worked OK for me.

I managed to upload 1 track. Then the next.. 

: GetUploadSession error 404: the request was rejected
(1/1)  Failed to upload 08-10-2015.mp3  |  ALREADY EXISTS

and then subsequent requests

 rejected: TrackSampleResponse code 4: ALREADY_EXISTS(bb9971d7-db54-3bf0-820f-3df143d57f23)
(1/1)  Failed to upload 08-10-2015.mp3  |  ALREADY EXISTS

Hope you can resolve it :-)

**Comment by jmk2000** [comment] 2015-11-26 07:55
@simon-weber the tracks were not changed at all; this was before the 404/ALREADY_EXISTS started.

It's making me think though that there has always been something different about the metadata of content uploaded by the API which until recently was tolerated by the backend

**Comment by antoniocosta** [comment] 2015-11-30 03:10
Same problem here.
First attempt to upload a song: *GetUploadSession error 404: the request was rejected*
All subsequent attempts: *ALREADY EXISTS*
Python 2.7.3, gmusicapi 7.0.0

**Comment by accandme** [comment] 2015-11-30 16:04
Guys, do you think there is hope that this will be fixed, one day?

**Comment by simon-weber** [comment] 2015-11-30 20:07
I think so. The eyed3 workaround (https://github.com/simon-weber/gmusicapi/issues/380#issuecomment-156743098) at least works sometimes. The next step is to do the same tag stripping when calculating the clientid.

I've been pretty busy with other things recently and haven't spent time on it since last weekend.

**Comment by siebert** [comment] 2015-12-01 09:14
Simon, did you only use the commandline version of eyed3 as described in the workaround or did you already wrote some python code to strip the tags using eyed3 as a library? If the latter, can you share that code?

**Comment by simon-weber** [comment] 2015-12-01 12:23
@siebert I've only used the command line interface.

Hopefully I'll have time this weekend to switch how the client id is generated.

**Comment by peterquest** [comment] 2015-12-03 03:40
just adding 2 cents that the eyed3 workaround doesn't solve anything for me. didn't realize how often I rely on this until this bug cropped up. sad!!! :(

**Comment by ezhikus** [comment] 2015-12-03 08:13
for me eyed3 workaround helps only for a few tracks, most tracks still couldn't be uploaded even with stripped tags

**Comment by adam-uk** [comment] 2015-12-09 22:34
Any update on this? Hopefully you'll find some time soon :-)

**Comment by simon-weber** [comment] 2015-12-10 01:02
Sorry, no tangible progress to share =(

Worst comes to worst, I'll definitely have time over the holidays.

**Comment by poupougnac** [comment] 2015-12-10 09:10
+1 will be so happy to see this working again ;) Thank you

**Comment by riha13** [comment] 2015-12-12 02:10
https://www.reddit.com/r/Android/comments/3we5sc/new_feature_saved_a_song_in_my_google_drive/

could this be a workaround?

**Comment by xKyloRenx** [comment] 2015-12-12 02:20
https://www.reddit.com/r/Android/comments/3we5sc/new_feature_saved_a_song_in_my_google_drive/

Could this be a workaround?

**Comment by simon-weber** [comment] 2015-12-12 17:40
@xKyloRenx interesting. Can anyone here corroborate that adding songs to Drive makes them show up in Music?

I keep all my music backed up in Drive and haven't noticed duplicates or anything.

**Comment by accandme** [comment] 2015-12-13 23:37
The Drive "solution" does not work for me.

FWIW, I tried chunking a 3-minute song into three 1-minute files. The three chunks uploaded perfectly. The problem seems to be related to the length of the song. Songs that are less than 1 minute long are generally succeeding. Longer songs are generally failing...

**Comment by simon-weber** [comment] 2015-12-14 00:54
That does line up with my test suite's short track succeeding to upload, but it may also have to do with Google not requesting a match, which was something I suspected earlier: https://github.com/simon-weber/gmusicapi/issues/380#issuecomment-156465847.

Can someone think of a short, popular track (that's likely to generate a match) and try to upload it?

**Comment by adam-uk** [comment] 2015-12-15 23:53
>Can someone think of a short, popular track (that's likely to generate a match) and try to upload it?
I thought that required a subscription, but I guess not (otherwise I would have tried sooner)

So I purchased a track from Amazon. Empire of the sun - Alive (fairly popular short track).

Test didn't go quite as planned as I had moved failed uploads to a tmp directory, and the uploader could still see them, but anyway it still failed..

2 differences found.
WARNING:gmusicapi.Musicmanager1:giving up on upload session for '/music/01 - Alive.mp3': GetUploadSession error 404: the request was rejected
(1/2)  Failed to upload  /music/01 - Alive.mp3  |  ALREADY EXISTS

I've uploaded the same track using the windows music manager and it appears it didn't match, so I need a track that will match.

**Comment by caffinatedmonkey** [comment] 2015-12-16 00:48
Fwiw I've never heard of that track. Try something like Justin Bieber or what ever the kids think is cool and hip today. :D


Sent from Outlook Mobile






On Tue, Dec 15, 2015 at 4:10 PM -0800, "adam-uk" <notifications@github.com> wrote:





>Can someone think of a short, popular track (that's likely to generate a match) and try to upload it?
I thought that required a subscription, but I guess not (otherwise I would have tried sooner)

So I purchased a track from Amazon. Empire of the sun - Alive (fairly popular short track).

Test didn't go quite as planned as I had moved failed uploads to a tmp directory, and the uploader could still see them, but anyway it still failed..

2 differences found.
WARNING:gmusicapi.Musicmanager1:giving up on upload session for '/music/01 - Alive.mp3': GetUploadSession error 404: the request was rejected
(1/2)  Failed to upload  /music/01 - Alive.mp3  |  ALREADY EXISTS

I've uploaded the same track using the windows music manager and it appears it didn't match, so I need a track that will match.



---

**Comment by thebigmunch** [comment] 2015-12-16 01:58
@adam-uk You should really do the tests directly with gmusicapi. You're using a script that just copypasta'd code from my scripts (a version from years ago) which disables matching anyway. Also, it's been abandoned for quite some time as well.

**Comment by robertlarousso** [comment] 2016-01-04 20:40
First of all, thank you very Simon for your hard work on this api :+1: (and happy new year).
Have you got any news on this bug ? 
On my raspberry I can't upload any song snif ;-(

**Comment by simon-weber** [comment] 2016-01-06 06:16
Sorry, I don't have any updates :disappointed:

**Comment by bong0** [comment] 2016-01-08 00:50
I'm having the exact same issue, but just were successful in exporting the specific track of a audiobook to .m4a with audacity and then uploading it in music manager on my linux box

**Comment by robertlarousso** [comment] 2016-01-11 06:50
I don't know what happend but since yesterday it works for every song I uploaded...
Maybe there is a correlation with the file name.

**Comment by FischerLouis** [comment] 2016-01-11 14:01
Hey guys,

Same here, all my uploads are going through since last week apparently ...

**Comment by thebigmunch** [comment] 2016-01-11 14:19
I can confirm the change in behavior, though I don't know if that should prevent a change being made to get gmusicapi to match Google Music's client id generation.

**Comment by simon-weber** [comment] 2016-01-11 15:38
Hmph. Well, I'm glad it's working again, even if it's not the most satisfying resolution. Anyone, feel free to reopen this if it starts happening again.

I'll open another issue to track the client id discrepancy.

**Comment by ScottESanDiego** [comment] 2016-01-11 17:58
It's still happening here.  Not sure closing this was really ready to close yet.

**Comment by simon-weber** [comment] 2016-01-11 18:13
Gotcha. How are other folks faring?

**Comment by thebigmunch** [comment] 2016-01-11 18:15
@ScottESanDiego: Are you testing on songs that you had previously attempted to upload while this problem was happening? If so, it might continue to show as already existing. I had used the Delete My Library option afterward which likely cleared away any remnants. As such, I can't test to see if that's the case. I have uploaded over 20 songs that previously exhibited this behavior and numerous more that I have never tried uploading previously. All were successful.

**Comment by ScottESanDiego** [comment] 2016-01-11 18:30
@thebigmunch Yes, I was just re-executing my sync scripts that had been failing.  I'm not eager to remove my whole library, but I'll give it a go...thanks for the idea.

**Comment by thebigmunch** [comment] 2016-01-11 18:40
Alternatively, if you have another Google account (or are willing to create a temporary one), you can use that to test on a fresh setup. If I'm right, deleting the entire library may be the only way to remove those remnant failures that don't show in the library.

**Comment by simon-weber** [comment] 2016-01-11 18:42
You might also want to try writing out a change to id3 tags on the file. That ought to bypass a check for duplicate client ids on their end.

**Comment by siebert** [comment] 2016-01-11 22:23
Hm. I tried to upload an album where all tracks were reported as matched, but only one track actually appeared in the library (with a wrong cover). I removed the track, changed the id3 tags, tried again, all tracks were again reported as matched and this time all appeared in the library (but still with the wrong cover). I had to manually delete the cover and upload the correct image, but so far it looks promising.

I also noticed since a few days, that I always get a warning email from google that I had logged into my account everytime I authenticate via gmusicapi. Is there a way to prevent this?

**Comment by adam-uk** [comment] 2016-01-11 23:26
"thebigmunch commented 27 days ago

@adam-uk You should really do the tests directly with gmusicapi. You're using a script that just copypasta'd code from my scripts (a version from years ago) which disables matching anyway. Also, it's been abandoned for quite some time as well."

Sorry about that, I use a weird setup (cloud based) so I'm restricted to what I can install -  that solution previously worked well for me.

I would be happy to send a track to someone privately that I can see has been matched (that's been uploaded by the windows manager) so they can try the test which is "Can someone think of a short, popular track (that's likely to generate a match) and try to upload it?" although seem things have possibly progressed a bit since that idea.

Also, this evening I've tested that 'blacklisted' tracks that still refuse to upload using the gmusicapi do upload with the windows manager without any id3 tag or other editing.

**Comment by simon-weber** [comment] 2016-01-13 12:11
@siebert re "I always get a warning email from google that I had logged into my account", I'm only aware of that happening with the webclient (https://github.com/simon-weber/gmusicapi/issues/395). Is it happening with other clients for you?

**Comment by siebert** [comment] 2016-01-13 12:47
My upload script uses mobileclient, webclient and musicmanager (logs into all three of them) and for each run I got two mails from google, so it seems that two of the three clients had the issue, but I have no idea which ones.

But at some point google stopped to send the mails, I don't know why.

I also uploaded a couple of albums (some matched, others not) and everything is working fine again.

**Comment by caffinatedmonkey** [comment] 2016-01-13 14:02
This is not a new issue and has happened to me in the past. I was using the default client for gmusic-scripts.

**Comment by simon-weber** [comment] 2016-01-31 04:25
Is anyone still seeing this problem?

**Comment by thebigmunch** [comment] 2016-01-31 12:45
I haven't seen it crop up at all since I confirmed the behavior change 3 weeks ago. It'd be nice to know how @ScottESanDiego fared.

**Comment by ezhikus** [comment] 2016-01-31 13:56
Everything works fine now.

**Comment by simon-weber** [comment] 2016-01-31 14:40
Great. I'll close again -- let me know if anyone sees this later on.

**Closed by simon-weber** 2016-01-31 14:40 UTC
Labels: bug

**Comment by ScottESanDiego** [comment] 2016-01-31 17:24
Sorry, got called away and didn't get a chance to test.  Indeed, it looks like it's working fine for me now (with -develop/-devel branches of everything).
