### ISSUE TITLE
Mobileclient.search(): no song_hits from my uploaded songs

### ISSUE THREAD

**Issue by darryllee** [simon-weber/gmusicapi#623] opened 2018-10-22 00:51 UTC
Hi, not sure if this is related to #622 . I'm trying to use geemusic to play songs that I've manually uploaded to Google Music (not available on Google Play Music, even if I pay).

Doing a search for "me myself and i de la soul" (song + artist), I get 'song_hits': [].

When I search for "me myself and i" I get 1 hit, but it's not the one in my album, which *does* show up when I do get_all_songs.

Is this expected behavior (Search does not look in uploaded songs?)

Should I consider modifying geemusic to just use get_all_songs as a local searchable index of my songs, since that's all I'm really concerned with playing?

Thanks!

**Comment by simon-weber** [comment] 2018-10-22 16:02
This looks like an accidental dupe of #625.

**Closed by simon-weber** 2018-10-22 16:02 UTC
