### ISSUE TITLE
Upload TypeError: Can't convert 'bytes' object to str implicitly

### ISSUE THREAD

**Issue by totalretribution** [simon-weber/gmusicapi#446] opened 2016-03-30 12:24 UTC
I get the error TypeError: Can't convert 'bytes' object to str implicitly when I try to upload any songs.
This is using python 3.4.4 in a virtualenv.

I use the following code:

```
from gmusicapi import Musicmanager

api = Musicmanager()
api.login(oauth_credentials="oauth.cred")
api.upload("light.flac",enable_matching=True)
api.logout()

```

and pip freeze provides the following
```
appdirs==1.4.0
beautifulsoup4==4.4.1
cffi==1.5.2
cryptography==1.3.1
decorator==4.0.9
docopt-unicode==0.6.1
future==0.15.2
gmusicapi==9.0.0
gmusicapi-scripts==0.3.0
gmusicapi-wrapper==0.3.0
gpsoauth==0.2.0
httplib2==0.9.2
idna==2.1
MechanicalSoup==0.4.0
mock==1.3.0
mutagen==1.31
ndg-httpsclient==0.4.0
oauth2client==2.0.1
pbr==1.8.1
proboscis==1.2.6.0
protobuf==3.0.0b2
pyasn1==0.1.9
pyasn1-modules==0.0.8
pycparser==2.14
pycryptodome==3.4
pyOpenSSL==16.0.0
python-dateutil==2.5.1
requests==2.7.0
rsa==3.4.1
six==1.10.0
validictory==1.0.1
```
and the error i get is
```
Traceback (most recent call last):
  File "upload.py", line 5, in <module>
    api.upload("light.flac",enable_matching=True)
  File "<decorator-gen-68>", line 2, in upload
  File "/home/user/vegmusicapi-scripts/lib/python3.4/site-packages/gmusicapi/utils/utils.py", line 619, in wrapper
    return function(*args, **kw)
  File "<decorator-gen-67>", line 2, in upload
  File "/home/user/vegmusicapi-scripts/lib/python3.4/site-packages/gmusicapi/utils/utils.py", line 596, in wrapper
    return function(*args, **kw)
  File "/home/user/vegmusicapi-scripts/lib/python3.4/site-packages/gmusicapi/clients/musicmanager.py", line 495, in upload
    self.uploader_id, bogus_sample)
  File "/home/user/vegmusicapi-scripts/lib/python3.4/site-packages/gmusicapi/clients/shared.py", line 83, in _make_call
    return protocol.perform(self.session, self.validate, *args, **kwargs)
  File "/home/user/vegmusicapi-scripts/lib/python3.4/site-packages/gmusicapi/protocol/shared.py", line 208, in perform
    req_kwargs = cls.build_request(*args, **kwargs)
  File "/home/user/vegmusicapi-scripts/lib/python3.4/site-packages/gmusicapi/protocol/shared.py", line 90, in build_request
    val = val(*args, **kwargs)
  File "<decorator-gen-59>", line 2, in dynamic_data
  File "/home/user/vegmusicapi-scripts/lib/python3.4/site-packages/gmusicapi/protocol/musicmanager.py", line 72, in pb
    msg = f(*args, **kwargs)
  File "/home/user/vegmusicapi-scripts/lib/python3.4/site-packages/gmusicapi/protocol/musicmanager.py", line 528, in dynamic_data
    slice_duration=sample_spec.duration_millis // 1000
  File "/home/user/vegmusicapi-scripts/lib/python3.4/site-packages/gmusicapi/utils/utils.py", line 508, in transcode_to_mp3
    err_output = ("(return code: %r)\n" % proc.returncode) + err_output
TypeError: Can't convert 'bytes' object to str implicitly

```

**Comment by tjstum** [comment] 2016-03-30 17:13
I can probably take a look at this later tonight. It seems that there's some other actual issue, but the error gets lost.

**Comment by thebigmunch** [comment] 2016-03-30 17:37
If you can go into the utils.py file, change the specified line (508) to ``err_output = ("(return code: %r)\n" % proc.returncode) + str(err_output)``. That should take care of the bytes/str coercion caused by Popen.communicate() returning bytes unless it had ``universal_newlines=True`` when instantiated. Then you should hopefully get to see what the real error was.

**Comment by totalretribution** [comment] 2016-03-30 17:52
Thanks for that, I made the change and now get an actual error related to ffmpeg which was my suspicion originally. I will investigate this and most likely I will have to compile ffmpeg.

Just in case you want to see it the error I now get is
```
2016-03-30 18:47:25,420 - gmusicapi.Musicmanager1 (utils:522) [ERROR]: transcoding failure:
transcoding command (/usr/bin/ffmpeg -i light.flac -t 60 -ss 101 -b:a 128k -f s16le -c libmp3lame pipe:1) failed: .
stderr: '(return code: 1)
b"ffmpeg version 0.8.17-6:0.8.17-2, Copyright (c) 2000-2014 the Libav developers\n  built on Mar  2 2016 22:53:14 with gcc 4.7.2\nThe ffmpeg program is only provided for script compatibility and will be removed\nin a future release. It has been deprecated in the Libav project to allow for\nincompatible command line syntax improvements in its replacement called avconv\n(see Changelog for details). Please use avconv instead.\n[flac @ 0x1539b60] max_analyze_duration reached\nInput #0, flac, from 'light.flac':\n  Metadata:\n    ALBUM           : This Unruly Mess I've Made\n    album_artist    : Macklemore & Ryan Lewis\n    ARTIST          : Macklemore & Ryan Lewis\n    COPYRIGHT       : 2016 Macklemore, LLC\n    DATE            : 2016\n    DESCRIPTION     : Purchased from 7digital.com\n    GENRE           : Hip Hop\n    TITLE           : Light Tunnels (feat. Mike Slap) Explicit\n    DISCTOTAL       : 1\n    TRACKTOTAL      : 13\n    track           : 1\n  Duration: 00:06:37.70, bitrate: 903 kb/s\n    Stream #0.0: Audio: flac, 44100 Hz, 2 channels, s16\nUnrecognized option 'c'\nFailed to set value 'libmp3lame' for option 'c'\n"'
Traceback (most recent call last):
  File "/home/user/vegmusicapi-scripts/lib/python3.4/site-packages/gmusicapi/utils/utils.py", line 510, in transcode_to_mp3
    raise IOError  # handle errors in except
OSError
2016-03-30 18:47:25,421 - gmusicapi.Musicmanager1 (musicmanager:499) [WARNING]: couldn't create scan and match sample for 'light.flac': transcoding command (/usr/bin/ffmpeg -i light.flac -t 60 -ss 101 -b:a 128k -f s16le -c libmp3lame pipe:1) failed: .
stderr: '(return code: 1)
b"ffmpeg version 0.8.17-6:0.8.17-2, Copyright (c) 2000-2014 the Libav developers\n  built on Mar  2 2016 22:53:14 with gcc 4.7.2\nThe ffmpeg program is only provided for script compatibility and will be removed\nin a future release. It has been deprecated in the Libav project to allow for\nincompatible command line syntax improvements in its replacement called avconv\n(see Changelog for details). Please use avconv instead.\n[flac @ 0x1539b60] max_analyze_duration reached\nInput #0, flac, from 'light.flac':\n  Metadata:\n    ALBUM           : This Unruly Mess I've Made\n    album_artist    : Macklemore & Ryan Lewis\n    ARTIST          : Macklemore & Ryan Lewis\n    COPYRIGHT       : 2016 Macklemore, LLC\n    DATE            : 2016\n    DESCRIPTION     : Purchased from 7digital.com\n    GENRE           : Hip Hop\n    TITLE           : Light Tunnels (feat. Mike Slap) Explicit\n    DISCTOTAL       : 1\n    TRACKTOTAL      : 13\n    track           : 1\n  Duration: 00:06:37.70, bitrate: 903 kb/s\n    Stream #0.0: Audio: flac, 44100 Hz, 2 channels, s16\nUnrecognized option 'c'\nFailed to set value 'libmp3lame' for option 'c'\n"'
```

**Comment by simon-weber** [comment] 2016-04-07 03:07
Oh, whoops, I'm not sure if that commit fixes the root issue? I'll leave it open till I hear back; don't want to close it out from under you.

**Closed** 2016-05-01 18:09 UTC
