### ISSUE TITLE
Ubuntu 15.04: OSError: a valid MAC could not be determined. Provide an android_id (and be sure to provide the same one on future runs).

### ISSUE THREAD

**Issue by lelandbatey** [simon-weber/gmusicapi#418] opened 2016-02-24 06:57 UTC
On Ubuntu 15.04 (technically Xubuntu 15.04), I am getting the following error when attempting to use the program `gmusic-playlist`, which makes use of this library:

    Traceback (most recent call last):
      File "ImportList.py", line 193, in <module>
        api = open_api()
      File "/home/leland/projects/python-projects/gmusic-playlist/common.py", line 162, in open_api
        if not api.login(username, password, Mobileclient.FROM_MAC_ADDRESS):
      File "/home/leland/bin/venv/local/lib/python2.7/site-packages/gmusicapi/clients/mobileclient.py", line 60, in login
        raise OSError("a valid MAC could not be determined."
    OSError: a valid MAC could not be determined. Provide an android_id (and be sure to provide the same one on future runs).

I cannot figure out why this would be the case. Additionally, the laptop that I am encountering this on is one without an ethernet port, so I only have wifi to connect with, otherwise I'd try a wired connection.

Additionally, my wifi hardware (found using `lspci`) is apparently an `Intel Corporation Wireless 7260 (rev cb)`. Don't know if that will help out, but I include it in the off chance that it might.

If there is additional information I can provide or work I can do to attempt to find the root of this problem, let me know, and thank you for the work on this project so far!

**Comment by simon-weber** [comment] 2016-02-24 16:04
Looks like this is a duplicate of https://github.com/simon-weber/gmusicapi/issues/408. I wonder if the python 3 changes broke mac address detection?

Anywho, let's merge this into the other issue.

**Closed by simon-weber** 2016-02-24 16:04 UTC
