### ISSUE TITLE
Use of future library breaks compatibility with Google App Engine environment

### ISSUE THREAD

**Issue by sciencepro** [simon-weber/gmusicapi#445] opened 2016-03-28 03:18 UTC
I'm still researching this, but it appears that the use of the `future` library and call to `standard_library.install_aliases()` has an internal requirement of the `subprocess` module, which is not supported on Google App Engine and was not previously a requirement to use gmusicapi.

Is there a workaround for those of us who don't care about Python 3 and wish to retain GAE compatibility?

**Comment by thebigmunch** [comment] 2016-03-31 22:34
I'm gonna be fairly blunt here.

subprocess was already a requirement of gmusicapi but only for uploading. Since Google App Engine doesn't support subprocesses, it already didn't fully support gmusicapi. While Google App Engine is certainly great, there are other PAAS services that simply don't have these limitations. I don't think its in the best interest of gmusicapi development to be concerned with keeping compatibility with one service that limits some basic functionality gmusicapi uses or may use in the future.

I really think the best option is for you (or someone else) to create a fork of gmusicapi that maintains proper GAE compatibility if there's that much interest in it.

All that said, you'd need to wait for @simon-weber to respond for an official stance on it.

**Comment by simon-weber** [comment] 2016-04-02 16:37
Maybe you could mutate the module cache to stub out subprocess before importing gmusicapi? That way, when install_aliases imports it, it doesn't immediately crash?

@thebigmunch's comment is close to my feelings. If we can maintain GAE compatibility without big sacrifices: great, I'm happy to merge fixes. Or, maybe there's a way we can better degrade for specific clients, by eg deferring imports to isolate them to parts GAE users aren't likely to need. But since we don't have a great way of testing for GAE regressions, already ship backwards-incompatible changes regularly, and (I think?) don't have a huge amount of GAE users, maintaining compatibility doesn't currently have a great cost/benefit ratio.

**Comment by thebigmunch** [comment] 2016-09-17 20:39
@sciencepro or anyone else using GAE: Was this fixed in #496? It hasn't hit release yet, but you can test by installing the develop branch.

**Comment by simon-weber** [comment] 2020-01-09 23:50
I'm not sure if GAE works now, but https://github.com/simon-weber/gmusicapi/pull/659 removes `future` as a requirement.

**Closed by simon-weber** 2020-01-09 23:50 UTC
