### ISSUE TITLE
Cant get stream url

### ISSUE THREAD

**Issue by Randomneo** [simon-weber/gmusicapi#608] opened 2018-06-03 16:41 UTC
My code 
```
from gmusicapi import Mobileclient as Mobiclient

api = Mobiclient()

t = api.login('rostislav9999@gmail.com', 'mypass', Mobiclient.FROM_MAC_ADDRESS)
if (t):
    print("conected")
else:
    print("error while connection to google play music")
    quit()

library = api.get_all_songs()
track = library[0]
api.get_stream_url(track['id'])
```
Error message
```
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/gmusicapi/protocol/shared.py", line 218, in perform
    response.raise_for_status()
  File "/usr/lib/python3.6/site-packages/requests/models.py", line 935, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 403 Client Error: Forbidden for url: https://mclients.googleapis.com/music/mplay?opt=hi&net=mob&pt=e&slt=1528053940408&sig=kzoe5dlhm7ohH3D8StgYysDmZjI&songid=8b342856-c370-3cca-9365-8f8e6bf89a46&hl=en_US&dv=0&tier=aa

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "main.py", line 14, in <module>
    api.get_stream_url(track['id'])
  File "<decorator-gen-102>", line 2, in get_stream_url
  File "/usr/lib/python3.6/site-packages/gmusicapi/utils/utils.py", line 293, in wrapper
    return function(*args, **kw)
  File "/usr/lib/python3.6/site-packages/gmusicapi/clients/mobileclient.py", line 393, in get_stream_url
    return self._make_call(mobileclient.GetStreamUrl, song_id, device_id, quality)
  File "/usr/lib/python3.6/site-packages/gmusicapi/clients/shared.py", line 84, in _make_call
    return protocol.perform(self.session, self.validate, *args, **kwargs)
  File "/usr/lib/python3.6/site-packages/gmusicapi/protocol/shared.py", line 226, in perform
    raise CallFailure(err_msg, call_name)
gmusicapi.exceptions.CallFailure: GetStreamUrl: 403 Client Error: Forbidden for url: https://mclients.googleapis.com/music/mplay?opt=hi&net=mob&pt=e&slt=1528053940408&sig=kzoe5dlhm7ohH3D8StgYysDmZjI&songid=8b342856-c370-3cca-9365-8f8e6bf89a46&hl=en_US&dv=0&tier=aa
(requests kwargs: {'method': 'GET', 'url': 'https://mclients.googleapis.com/music/mplay', 'allow_redirects': False, 'headers': {'X-Device-ID': '408D5CC9781E', 'Authorization': '<omitted>'}, 'params': {'opt': 'hi', 'net': 'mob', 'pt': 'e', 'slt': '1528053940408', 'sig': b'kzoe5dlhm7ohH3D8StgYysDmZjI', 'songid': '8b342856-c370-3cca-9365-8f8e6bf89a46', 'hl': 'en_US', 'dv': 0, 'tier': 'aa'}})
(response was: '<HTML>\n<HEAD>\n<TITLE>Forbidden</TITLE>\n</HEAD>\n<BODY BGCOLOR="#FFFFFF" TEXT="#000000">\n<H1>Forbidden</H1>\n<H2>Error 403</H2>\n</BODY>\n</HTML>\n')

```

**Comment by adnidor** [comment] 2018-06-03 17:56
This is (most likely) the same issue as documented in mopidy/mopidy-gmusic#192.

tldr: Don't use FROM_MAC_ADDRESS, use a proper device id instead

**Comment by simon-weber** [comment] 2018-06-03 17:59
Yup, looks like a duplicate of https://github.com/simon-weber/gmusicapi/issues/590.

**Closed by simon-weber** 2018-06-03 17:59 UTC
