### ISSUE TITLE
Some Warnings...

### ISSUE THREAD

**Issue by diegodeodati** [simon-weber/gmusicapi#528] opened 2017-02-03 17:31 UTC
Simon,
another problem...

UserWarning: implicit cast to 'char *' from a different pointer type: will be forbidden in the future

Here is the code:

from gmusicapi import Mobileclient

api = Mobileclient()
logged_in = api.login('#####@gmail.com', '#### #### #### ####', 'android')

any suggestion?
How i can disable warnings? i have

**Comment by simon-weber** [comment] 2017-02-03 18:19
I'm closing this as a duplicate of https://github.com/simon-weber/gmusicapi/issues/527.

**Closed by simon-weber** 2017-02-03 18:19 UTC
