### ISSUE TITLE
could not parse date md for ..: (month must be in 1..12) and ord() error

### ISSUE THREAD

**Issue by jimwd** [simon-weber/gmusicapi#559] opened 2017-06-19 16:38 UTC
An error i get when uploading certain mp3 files:

```
Uploading ./xx.mp3, options: MATCH=True, TYPE=0day
Match = True
2017-06-19 18:08:41,448 - gmusicapi.Musicmanager1 (musicmanager:298) [WARNING]: could not parse date md for ''./xx.mp3'': (month must be in 1..12)
Traceback (most recent call last):
  File "/usr/lib/python2.7/logging/__init__.py", line 861, in emit
    msg = self.format(record)
  File "/usr/lib/python2.7/logging/__init__.py", line 734, in format
    return fmt.format(record)
  File "/usr/lib/python2.7/logging/__init__.py", line 465, in format
    record.message = record.getMessage()
  File "/usr/lib/python2.7/logging/__init__.py", line 325, in getMessage
    msg = str(self.msg)
  File "/home/x/.local/lib/python2.7/site-packages/google/protobuf/internal/python_message.py", line 989, in __str__
    return text_format.MessageToString(self)
  File "/home/x/.local/lib/python2.7/site-packages/google/protobuf/text_format.py", line 159, in MessageToString
    printer.PrintMessage(message)
  File "/home/x/.local/lib/python2.7/site-packages/google/protobuf/text_format.py", line 326, in PrintMessage
    self.PrintField(field, value)
  File "/home/x/.local/lib/python2.7/site-packages/google/protobuf/text_format.py", line 355, in PrintField
    self.PrintFieldValue(field, value)
  File "/home/x/.local/lib/python2.7/site-packages/google/protobuf/text_format.py", line 391, in PrintFieldValue
    self._PrintMessageFieldValue(value)
  File "/home/x/.local/lib/python2.7/site-packages/google/protobuf/text_format.py", line 376, in _PrintMessageFieldValue
    self.PrintMessage(value)
  File "/home/x/.local/lib/python2.7/site-packages/google/protobuf/text_format.py", line 324, in PrintMessage
    self.PrintField(field, element)
  File "/home/x/.local/lib/python2.7/site-packages/google/protobuf/text_format.py", line 355, in PrintField
    self.PrintFieldValue(field, value)
  File "/home/x/.local/lib/python2.7/site-packages/google/protobuf/text_format.py", line 391, in PrintFieldValue
    self._PrintMessageFieldValue(value)
  File "/home/x/.local/lib/python2.7/site-packages/google/protobuf/text_format.py", line 376, in _PrintMessageFieldValue
    self.PrintMessage(value)
  File "/home/x/.local/lib/python2.7/site-packages/google/protobuf/text_format.py", line 326, in PrintMessage
    self.PrintField(field, value)
  File "/home/x/.local/lib/python2.7/site-packages/google/protobuf/text_format.py", line 355, in PrintField
    self.PrintFieldValue(field, value)
  File "/home/x/.local/lib/python2.7/site-packages/google/protobuf/text_format.py", line 409, in PrintFieldValue
    out.write(text_encoding.CEscape(out_value, out_as_utf8))
  File "/home/x/.local/lib/python2.7/site-packages/google/protobuf/text_encoding.py", line 79, in CEscape
    return ''.join(_cescape_byte_to_str[Ord(c)] for c in text)
  File "/home/x/.local/lib/python2.7/site-packages/google/protobuf/text_encoding.py", line 79, in <genexpr>
    return ''.join(_cescape_byte_to_str[Ord(c)] for c in text)
TypeError: ord() expected string of length 1, but int found
```

**Comment by simon-weber** [comment] 2017-06-19 16:41
I think this is a dupe of https://github.com/simon-weber/gmusicapi/issues/452. The month warning looks like a red herring to me.

Cool with me closing this? We can continue discussing on the other issue.

**Comment by jimwd** [comment] 2017-06-19 16:43
Fine with that.. But what do you mean with a red herring?

**Comment by simon-weber** [comment] 2017-06-19 16:44
Ah, I mean the warning about the date is probably unrelated to the TypeError (mostly since the other issue doesn't have it in the traceback).

**Closed by simon-weber** 2017-06-19 16:44 UTC
