### ISSUE TITLE
UnicodeEncodeError: 'ascii' codec can't encode characters in position 10-11: ordinal not in range(128)

### ISSUE THREAD

**Issue by shaneholloman** [simon-weber/gmusicapi#394] opened 2016-01-08 00:13 UTC
https://github.com/thebigmunch/gmusicapi-scripts/issues/52#issuecomment-169818598

All songs synced up to, but not including this song:
`El Mañana (Metronomy Remix) -- Gorillaz -- D-Sides (697e7789-87f3-39e6-bd70-7abcc89743f3)`

I think the `ñ` could be causing the issue ...

When I make a dry run there is no problem using:
`$ gmsync down -m -d  "/Volumes/1A/clouds/google/shaneholloman@gmail.com/shane/Music/Google/%artist%/%album%/%title%"`
This command will comfortably list all missing songs, including the song with the word `Mañana` in it

But when I execute a sync using:
`$ gmsync down -m  "/Volumes/1A/clouds/google/shaneholloman@gmail.com/shane/Music/Google/%artist%/%album%/%title%"`

I get this notice:
`UnicodeEncodeError: 'ascii' codec can't encode characters in position 10-11: ordinal not in range(128)`

Here's the complete output:
```
Scanning for missing songs...

Downloading 252 song(s) from Google Music

Traceback (most recent call last):
  File "/usr/local/bin/gmsync", line 9, in <module>
    load_entry_point('gmusicapi-scripts==0.1.0', 'console_scripts', 'gmsync')()
  File "/usr/local/lib/python2.7/site-packages/gmusicapi_scripts-0.1.0-py2.7.egg/gmusicapi_scripts/gmsync.py", line 180, in main
    mmw.download(songs_to_download, cli['output'])
  File "<decorator-gen-114>", line 2, in download
  File "/usr/local/lib/python2.7/site-packages/gmusicapi-7.0.1.dev0-py2.7.egg/gmusicapi/utils/utils.py", line 612, in wrapper
    return function(*args, **kw)
  File "/usr/local/lib/python2.7/site-packages/gmusicapi_wrapper-0.1.0-py2.7.egg/gmusicapi_wrapper/gmusicapi_wrapper.py", line 394, in download
    for result in self._download(songs, template):
  File "/usr/local/lib/python2.7/site-packages/gmusicapi_wrapper-0.1.0-py2.7.egg/gmusicapi_wrapper/gmusicapi_wrapper.py", line 331, in _download
    suggested_filename, audio = self.api.download_song(song_id)
  File "<decorator-gen-60>", line 2, in download_song
  File "/usr/local/lib/python2.7/site-packages/gmusicapi-7.0.1.dev0-py2.7.egg/gmusicapi/utils/utils.py", line 290, in wrapper
    return function(*args, **kw)
  File "/usr/local/lib/python2.7/site-packages/gmusicapi-7.0.1.dev0-py2.7.egg/gmusicapi/clients/musicmanager.py", line 350, in download_song
    filename = filename.decode('utf-8')
  File "/usr/local/Cellar/python/2.7.11/Frameworks/Python.framework/Versions/2.7/lib/python2.7/encodings/utf_8.py", line 16, in decode
    return codecs.utf_8_decode(input, errors, True)
UnicodeEncodeError: 'ascii' codec can't encode characters in position 10-11: ordinal not in range(128)
```

**Comment by thebigmunch** [comment] 2016-01-08 01:13
Just so it is here. This is caused by a side-effect of the futurize level 1 changes. The response filename in the download_song method ends up being unicode rather than str so the decode results in an error.

**Comment by thebigmunch** [comment] 2016-01-29 21:45
#402 should hopefully fix this for you @shaneholloman

**Comment by shaneholloman** [comment] 2016-01-29 21:58
thank you @thebigmunch !

**Comment by simon-weber** [comment] 2016-01-31 04:23
I'm going to close this, but feel free to reopen if #402 did not address the problem.

**Closed by simon-weber** 2016-01-31 04:23 UTC
